INSERT INTO `countries` (`code`, `alpha3`, `numeric`, `continent`, `name`, `full_name`, `capital`) VALUES
('AF', 'AFG', '004', 'AS', 'Afghanistan', 'the Islamic Republic of Afghanistan', 'Kabul'),
('AX', 'ALA', '248', 'EU', 'Åland Islands', 'Åland Islands', 'Mariehamn'),
('AL', 'ALB', '008', 'EU', 'Albania', 'the Republic of Albania', 'Tirana'),
('DZ', 'DZA', '012', 'AF', 'Algeria', 'the People\'s Democratic Republic of Algeria', 'Algiers'),
('AS', 'ASΜ', '016', 'OC', 'American Samoa', 'American Samoa', 'Pago Pago'),
('AD', 'AND', '020', 'EU', 'Andorra', 'the Principality of Andorra', 'Andorra la Vella'),
('AO', 'AGO', '024', 'AF', 'Angola', 'the Republic of Angola', 'Luanda'),
('AI', 'AIA', '660', 'NA', 'Anguilla', 'Anguilla', 'The Valley'),
('AQ', 'ΑΤΑ', '010', 'AN', 'Antarctica', 'Antarctica', ''),
('AG', 'ATG', '028', 'NA', 'Antigua and Barbuda', 'Antigua and Barbuda', 'St. John\'s'),
('AR', 'ARG', '032', 'SA', 'Argentina', 'the Argentine Republic', 'Buenos Aires'),
('AM', 'ARM', '051', 'AS', 'Armenia', 'the Republic of Armenia', 'Yerevan'),
('AW', 'ABW', '533', 'NA', 'Aruba', 'Aruba', 'Oranjestad'),
('AU', 'AUS', '036', 'OC', 'Australia', 'Australia', 'Canberra'),
('AT', 'AUT', '040', 'EU', 'Austria', 'the Republic of Austria', 'Vienna'),
('AZ', 'AZE', '031', 'AS', 'Azerbaijan', 'the Republic of Azerbaijan', 'Baku'),
('BS', 'BHS', '044', 'NA', 'Bahamas', 'the Commonwealth of the Bahamas', 'Nassau'),
('BH', 'BHR', '048', 'AS', 'Bahrain', 'the Kingdom of Bahrain', 'Manama'),
('BD', 'BGD', '050', 'AS', 'Bangladesh', 'the People\'s Republic of Bangladesh', 'Dhaka'),
('BB', 'BRB', '052', 'NA', 'Barbados', 'Barbados', 'Bridgetown'),
('BY', 'BLR', '112', 'EU', 'Belarus', 'the Republic of Belarus', 'Minsk'),
('BE', 'BEL', '056', 'EU', 'Belgium', 'the Kingdom of Belgium', 'Brussels'),
('BZ', 'BLZ', '084', 'NA', 'Belize', 'Belize', 'Belmopan'),
('BJ', 'BEN', '204', 'AF', 'Benin', 'the Republic of Benin', 'Porto-Novo'),
('BM', 'BMU', '060', 'NA', 'Bermuda', 'Bermuda', 'Hamilton'),
('BT', 'BTN', '064', 'AS', 'Bhutan', 'the Kingdom of Bhutan', 'Thimphu'),
('BO', 'BOL', '068', 'SA', 'Bolivia, Plurinational State of', 'the Plurinational State of Bolivia', 'Sucre'),
('BQ', 'BES', '535', 'NA', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'Kralendijk'),
('BA', 'BIH', '070', 'EU', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Sarajevo'),
('BW', 'BWA', '072', 'AF', 'Botswana', 'the Republic of Botswana', 'Gaborone'),
('BV', 'BVT', '074', 'AN', 'Bouvet Island', 'Bouvet Island', ''),
('BR', 'BRA', '076', 'SA', 'Brazil', 'the Federative Republic of Brazil', 'Brasília'),
('IO', 'IOT', '086', 'AS', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'Camp Justice'),
('BN', 'BRN', '096', 'AS', 'Brunei Darussalam', 'Brunei Darussalam', 'Bandar Seri Begawan'),
('BG', 'BGR', '100', 'EU', 'Bulgaria', 'the Republic of Bulgaria', 'Sofia'),
('BF', 'BFA', '854', 'AF', 'Burkina Faso', 'Burkina Faso', 'Ouagadougou'),
('BI', 'BDI', '108', 'AF', 'Burundi', 'the Republic of Burundi', 'Bujumbura'),
('CV', 'CPV', '132', 'AF', 'Cabo Verde', 'the Republic of Cabo Verde', 'Praia'),
('KH', 'KHM', '116', 'AS', 'Cambodia', 'the Kingdom of Cambodia', 'Phnom Penh'),
('CM', 'CMR', '120', 'AF', 'Cameroon', 'the Republic of Cameroon', 'Yaoundé'),
('CA', 'CAN', '124', 'NA', 'Canada', 'Canada', 'Ottawa'),
('KY', 'CYM', '136', 'NA', 'Cayman Islands', 'Cayman Islands', 'George Town'),
('CF', 'CAF', '140', 'AF', 'Central African Republic', 'the Central African Republic', 'Bangui'),
('TD', 'TCD', '148', 'AF', 'Chad', 'the Republic of Chad', 'N\'Djamena'),
('CL', 'CHL', '152', 'SA', 'Chile', 'the Republic of Chile', 'Santiago'),
('CN', 'CHN', '156', 'AS', 'China', 'the People\'s Republic of China', 'Beijing'),
('CX', 'CXR', '162', 'AS', 'Christmas Island', 'Christmas Island', 'Flying Fish Cove'),
('CC', 'CCK', '166', 'AS', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'West Island'),
('CO', 'COL', '170', 'SA', 'Colombia', 'the Republic of Colombia', 'Bogotá'),
('KM', 'COM', '174', 'AF', 'Comoros', 'the Union of the Comoros', 'Moroni'),
('CD', 'COD', '180', 'AF', 'Congo, the Democratic Republic of the', 'the Democratic Republic of the Congo', 'Kinshasa'),
('CG', 'COG', '178', 'AF', 'Congo', 'the Republic of the Congo', 'Brazzaville'),
('CK', 'COK', '184', 'OC', 'Cook Islands', 'Cook Islands', 'Avarua'),
('CR', 'CRI', '188', 'NA', 'Costa Rica', 'the Republic of Costa Rica', 'San José'),
('CI', 'CIV', '384', 'AF', 'Côte d\'Ivoire', 'the Republic of Côte d\'Ivoire', 'Yamoussoukro'),
('HR', 'HRV', '191', 'EU', 'Croatia', 'the Republic of Croatia', 'Zagreb'),
('CU', 'CUB', '192', 'NA', 'Cuba', 'the Republic of Cuba', 'Havana'),
('CW', 'CUW', '531', 'NA', 'Curaçao', 'Curaçao', 'Willemstad'),
('CY', 'CYP', '196', 'EU', 'Cyprus', 'the Republic of Cyprus', 'Nicosia'),
('CZ', 'CZE', '203', 'EU', 'Czechia', 'the Czech Republic', 'Prague'),
('DK', 'DNK', '208', 'EU', 'Denmark', 'the Kingdom of Denmark', 'Copenhagen'),
('DJ', 'DJI', '262', 'AF', 'Djibouti', 'the Republic of Djibouti', 'Djibouti'),
('DM', 'DMA', '212', 'NA', 'Dominica', 'the Commonwealth of Dominica', 'Roseau'),
('DO', 'DOM', '214', 'NA', 'Dominican Republic', 'the Dominican Republic', 'Santo Domingo'),
('EC', 'ECU', '218', 'SA', 'Ecuador', 'the Republic of Ecuador', 'Quito'),
('EG', 'EGY', '818', 'AF', 'Egypt', 'the Arab Republic of Egypt', 'Cairo'),
('SV', 'SLV', '222', 'NA', 'El Salvador', 'the Republic of El Salvador', 'San Salvador'),
('GQ', 'GNQ', '226', 'AF', 'Equatorial Guinea', 'the Republic of Equatorial Guinea', 'Malabo'),
('ER', 'ERI', '232', 'AF', 'Eritrea', 'the State of Eritrea', 'Asmara'),
('EE', 'EST', '233', 'EU', 'Estonia', 'the Republic of Estonia', 'Tallinn'),
('ET', 'ETH', '231', 'AF', 'Ethiopia', 'the Federal Democratic Republic of Ethiopia', 'Addis Ababa'),
('FK', 'FLK', '238', 'SA', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', 'Stanley'),
('FO', 'FRO', '234', 'EU', 'Faroe Islands', 'Faroe Islands', 'Tórshavn'),
('FJ', 'FJI', '242', 'OC', 'Fiji', 'the Republic of Fiji', 'Suva'),
('FI', 'FIN', '246', 'EU', 'Finland', 'the Republic of Finland', 'Helsinki'),
('FR', 'FRA', '250', 'EU', 'France', 'the French Republic', 'Paris'),
('GF', 'GUF', '254', 'SA', 'French Guiana', 'French Guiana', 'Cayenne'),
('PF', 'PYF', '258', 'OC', 'French Polynesia', 'French Polynesia', 'Papeete'),
('TF', 'ATF', '260', 'AN', 'French Southern Territories', 'French Southern Territories', 'Port-aux-Français'),
('GA', 'GAB', '266', 'AF', 'Gabon', 'the Gabonese Republic', 'Libreville'),
('GM', 'GMB', '270', 'AF', 'Gambia', 'the Islamic Republic of the Gambia', 'Banjul'),
('GE', 'GEO', '268', 'AS', 'Georgia', 'Georgia', 'Tbilisi'),
('DE', 'DEU', '276', 'EU', 'Germany', 'the Federal Republic of Germany', 'Berlin'),
('GH', 'GHA', '288', 'AF', 'Ghana', 'the Republic of Ghana', 'Accra'),
('GI', 'GIB', '292', 'EU', 'Gibraltar', 'Gibraltar', 'Gibraltar'),
('GR', 'GRC', '300', 'EU', 'Greece', 'the Hellenic Republic of Greece', 'Athens'),
('GL', 'GRL', '304', 'NA', 'Greenland', 'Greenland', 'Nuuk'),
('GD', 'GRD', '308', 'NA', 'Grenada', 'Grenada', 'St. George\'s'),
('GP', 'GLP', '312', 'NA', 'Guadeloupe', 'Guadeloupe', 'Basse-Terre'),
('GU', 'GUM', '316', 'OC', 'Guam', 'Guam', 'Hagåtña'),
('GT', 'GTM', '320', 'NA', 'Guatemala', 'the Republic of Guatemala', 'Guatemala City'),
('GG', 'GGY', '831', 'EU', 'Guernsey', 'Guernsey', 'Saint Peter Port'),
('GN', 'GIN', '324', 'AF', 'Guinea', 'the Republic of Guinea', 'Conakry'),
('GW', 'GNB', '624', 'AF', 'Guinea-Bissau', 'the Republic of Guinea-Bissau', 'Bissau'),
('GY', 'GUY', '328', 'SA', 'Guyana', 'the Republic of Guyana', 'Georgetown'),
('HT', 'HTI', '332', 'NA', 'Haiti', 'the Republic of Haiti', 'Port-au-Prince'),
('HM', 'HMD', '334', 'AN', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', ''),
('VA', 'VAT', '336', 'EU', 'Holy See', 'Holy See', 'Vatican City'),
('HN', 'HND', '340', 'NA', 'Honduras', 'the Republic of Honduras', 'Tegucigalpa'),
('HK', 'HKG', '344', 'AS', 'Hong Kong', 'the Hong Kong Special Administrative Region of China', 'Hong Kong'),
('HU', 'HUN', '348', 'EU', 'Hungary', 'Hungary', 'Budapest'),
('IS', 'ISL', '352', 'EU', 'Iceland', 'the Republic of Iceland', 'Reykjavik'),
('IN', 'IND', '356', 'AS', 'India', 'the Republic of India', 'New Delhi'),
('ID', 'IDN', '360', 'AS', 'Indonesia', 'the Republic of Indonesia', 'Jakarta'),
('IR', 'IRN', '364', 'AS', 'Iran, Islamic Republic of', 'the Islamic Republic of Iran', 'Tehran'),
('IQ', 'IRQ', '368', 'AS', 'Iraq', 'the Republic of Iraq', 'Baghdad'),
('IE', 'IRL', '372', 'EU', 'Ireland', 'Ireland', 'Dublin'),
('IM', 'IMN', '833', 'EU', 'Isle of Man', 'Isle of Man', 'Douglas'),
('IL', 'ISR', '376', 'AS', 'Israel', 'the State of Israel', ''),
('IT', 'ITA', '380', 'EU', 'Italy', 'the Republic of Italy', 'Rome'),
('JM', 'JAM', '388', 'NA', 'Jamaica', 'Jamaica', 'Kingston'),
('JP', 'JPN', '392', 'AS', 'Japan', 'Japan', 'Tokyo'),
('JE', 'JEY', '832', 'EU', 'Jersey', 'Jersey', 'Saint Helier'),
('JO', 'JOR', '400', 'AS', 'Jordan', 'the Hashemite Kingdom of Jordan', 'Amman'),
('KZ', 'KAZ', '398', 'AS', 'Kazakhstan', 'the Republic of Kazakhstan', 'Astana'),
('KE', 'KEN', '404', 'AF', 'Kenya', 'the Republic of Kenya', 'Nairobi'),
('KI', 'KIR', '296', 'OC', 'Kiribati', 'the Republic of Kiribati', 'South Tarawa'),
('KP', 'PRK', '408', 'AS', 'Korea, the Democratic People\'s Republic of', 'the Democratic People\'s Republic of Korea', 'Pyongyang'),
('KR', 'KOR', '410', 'AS', 'Korea, the Republic of', 'the Republic of Korea', 'Seoul'),
('KW', 'KWT', '414', 'AS', 'Kuwait', 'the State of Kuwait', 'Kuwait City'),
('KG', 'KGZ', '417', 'AS', 'Kyrgyzstan', 'the Kyrgyz Republic', 'Bishkek'),
('LA', 'LAO', '418', 'AS', 'Lao People\'s Democratic Republic', 'the Lao People\'s Democratic Republic', 'Vientiane'),
('LV', 'LVA', '428', 'EU', 'Latvia', 'the Republic of Latvia', 'Riga'),
('LB', 'LBN', '422', 'AS', 'Lebanon', 'the Lebanese Republic', 'Beirut'),
('LS', 'LSO', '426', 'AF', 'Lesotho', 'the Kingdom of Lesotho', 'Maseru'),
('LR', 'LBR', '430', 'AF', 'Liberia', 'the Republic of Liberia', 'Monrovia'),
('LY', 'LBY', '434', 'AF', 'Libya', 'Libya', 'Tripoli'),
('LI', 'LIE', '438', 'EU', 'Liechtenstein', 'the Principality of Liechtenstein', 'Vaduz'),
('LT', 'LTU', '440', 'EU', 'Lithuania', 'the Republic of Lithuania', 'Vilnius'),
('LU', 'LUX', '442', 'EU', 'Luxembourg', 'the Grand Duchy of Luxembourg', 'Luxembourg City'),
('MO', 'MAC', '446', 'AS', 'Macao', 'Macao Special Administrative Region of China', 'Macao'),
('MK', 'MKD', '807', 'EU', 'Macedonia, the former Yugoslav Republic of', 'the former Yugoslav Republic of Macedonia', 'Skopje'),
('MG', 'MDG', '450', 'AF', 'Madagascar', 'the Republic of Madagascar', 'Antananarivo'),
('MW', 'MWI', '454', 'AF', 'Malawi', 'the Republic of Malawi', 'Lilongwe'),
('MY', 'MYS', '458', 'AS', 'Malaysia', 'Malaysia', 'Kuala Lumpur'),
('MV', 'MDV', '462', 'AS', 'Maldives', 'the Republic of Maldives', 'Malé'),
('ML', 'MLI', '466', 'AF', 'Mali', 'the Republic of Mali', 'Bamako'),
('MT', 'MLT', '470', 'EU', 'Malta', 'the Republic of Malta', 'Valletta'),
('MH', 'MHL', '584', 'OC', 'Marshall Islands', 'the Republic of the Marshall Islands', 'Majuro'),
('MQ', 'MTQ', '474', 'NA', 'Martinique', 'Martinique', 'Fort-de-France'),
('MR', 'MRT', '478', 'AF', 'Mauritania', 'the Islamic Republic of Mauritania', 'Nouakchott'),
('MU', 'MUS', '480', 'AF', 'Mauritius', 'the Republic of Mauritius', 'Port Louis'),
('YT', 'MYT', '175', 'AF', 'Mayotte', 'Mayotte', 'Mamoudzou'),
('MX', 'MEX', '484', 'NA', 'Mexico', 'the United Mexican States', 'Mexico City'),
('FM', 'FSM', '583', 'OC', 'Micronesia, Federated States of', 'the Federated States of Micronesia', 'Palikir'),
('MD', 'MDA', '498', 'EU', 'Moldova, the Republic of', 'the Republic of Moldova', 'Chişinău'),
('MC', 'MCO', '492', 'EU', 'Monaco', 'the Principality of Monaco', 'Monaco'),
('MN', 'MNG', '496', 'AS', 'Mongolia', 'Mongolia', 'Ulaanbaatar'),
('ME', 'MNE', '499', 'EU', 'Montenegro', 'Montenegro', 'Podgorica'),
('MS', 'MSR', '500', 'NA', 'Montserrat', 'Montserrat', 'Plymouth'),
('MA', 'MAR', '504', 'AF', 'Morocco', 'the Kingdom of Morocco', 'Rabat'),
('MZ', 'MOZ', '508', 'AF', 'Mozambique', 'the Republic of Mozambique', 'Maputo'),
('MM', 'MMR', '104', 'AS', 'Myanmar', 'the Republic of the Union of Myanmar', 'Naypyitaw'),
('NA', 'NAM', '516', 'AF', 'Namibia', 'the Republic of Namibia', 'Windhoek'),
('NR', 'NRU', '520', 'OC', 'Nauru', 'the Republic of Nauru', 'Yaren District'),
('NP', 'NPL', '524', 'AS', 'Nepal', 'the Federal Democratic Republic of Nepal', 'Kathmandu'),
('NL', 'NLD', '528', 'EU', 'Netherlands', 'the Kingdom of the Netherlands', 'Amsterdam'),
('NC', 'NCL', '540', 'OC', 'New Caledonia', 'New Caledonia', 'Nouméa'),
('NZ', 'NZL', '554', 'OC', 'New Zealand', 'New Zealand', 'Wellington'),
('NI', 'NIC', '558', 'NA', 'Nicaragua', 'the Republic of Nicaragua', 'Managua'),
('NE', 'NER', '562', 'AF', 'Niger', 'the Republic of the Niger', 'Niamey'),
('NG', 'NGA', '566', 'AF', 'Nigeria', 'the Federal Republic of Nigeria', 'Abuja'),
('NU', 'NIU', '570', 'OC', 'Niue', 'Niue', 'Alofi'),
('NF', 'NFK', '574', 'OC', 'Norfolk Island', 'Norfolk Island', 'Kingston'),
('MP', 'MNP', '580', 'OC', 'Northern Mariana Islands', 'the Commonwealth of the Northern Mariana Islands', 'Saipan'),
('NO', 'NOR', '578', 'EU', 'Norway', 'the Kingdom of Norway', 'Oslo'),
('OM', 'OMN', '512', 'AS', 'Oman', 'the Sultanate of Oman', 'Muscat'),
('PK', 'PAK', '586', 'AS', 'Pakistan', 'the Islamic Republic of Pakistan', 'Islamabad'),
('PW', 'PLW', '585', 'OC', 'Palau', 'the Republic of Palau', 'Ngerulmud'),
('PS', 'PSE', '275', 'AS', 'Palestine, State of', 'the State of Palestine', 'East Jerusalem'),
('PA', 'PAN', '591', 'NA', 'Panama', 'the Republic of Panama', 'Panama City'),
('PG', 'PNG', '598', 'OC', 'Papua New Guinea', 'the Independent State of Papua New Guinea', 'Port Moresby'),
('PY', 'PRY', '600', 'SA', 'Paraguay', 'the Republic of Paraguay', 'Asunción'),
('PE', 'PER', '604', 'SA', 'Peru', 'the Republic of Peru', 'Lima'),
('PH', 'PHL', '608', 'AS', 'Philippines', 'the Republic of the Philippines', 'Manila'),
('PN', 'PCN', '612', 'OC', 'Pitcairn', 'Pitcairn', 'Adamstown'),
('PL', 'POL', '616', 'EU', 'Poland', 'the Republic of Poland', 'Warsaw'),
('PT', 'PRT', '620', 'EU', 'Portugal', 'the Portuguese Republic', 'Lisbon'),
('PR', 'PRI', '630', 'NA', 'Puerto Rico', 'Puerto Rico', 'San Juan'),
('QA', 'QAT', '634', 'AS', 'Qatar', 'the State of Qatar', 'Doha'),
('RE', 'REU', '638', 'AF', 'Réunion', 'Réunion', 'Saint-Denis'),
('RO', 'ROU', '642', 'EU', 'Romania', 'Romania', 'Bucharest'),
('RU', 'RUS', '643', 'EU', 'Russian Federation', 'the Russian Federation', 'Moscow'),
('RW', 'RWA', '646', 'AF', 'Rwanda', 'the Republic of Rwanda', 'Kigali'),
('BL', 'BLM', '652', 'NA', 'Saint Barthélemy', 'Saint Barthélemy', 'Gustavia'),
('SH', 'SHN', '654', 'AF', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Jamestown'),
('KN', 'KNA', '659', 'NA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'Basseterre'),
('LC', 'LCA', '662', 'NA', 'Saint Lucia', 'Saint Lucia', 'Castries'),
('MF', 'MAF', '663', 'NA', 'Saint Martin (French part)', 'Saint Martin (French part)', 'Marigot'),
('PM', 'SPM', '666', 'NA', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'Saint-Pierre'),
('VC', 'VCT', '670', 'NA', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Kingstown'),
('WS', 'WSM', '882', 'OC', 'Samoa', 'the Independent State of Samoa', 'Apia'),
('SM', 'SMR', '674', 'EU', 'San Marino', 'the Republic of San Marino', 'San Marino'),
('ST', 'STP', '678', 'AF', 'São Tomé and Príncipe', 'the Democratic Republic of Sao Tome and Principe', 'São Tomé'),
('SA', 'SAU', '682', 'AS', 'Saudi Arabia', 'the Kingdom of Saudi Arabia', 'Riyadh'),
('SN', 'SEN', '686', 'AF', 'Senegal', 'the Republic of Senegal', 'Dakar'),
('RS', 'SRB', '688', 'EU', 'Serbia', 'the Republic of Serbia', 'Belgrade'),
('SC', 'SYC', '690', 'AF', 'Seychelles', 'the Republic of Seychelles', 'Victoria'),
('SL', 'SLE', '694', 'AF', 'Sierra Leone', 'the Republic of Sierra Leone', 'Freetown'),
('SG', 'SGP', '702', 'AS', 'Singapore', 'the Republic of Singapore', 'Singapore'),
('SX', 'SXM', '534', 'NA', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)', 'Philipsburg'),
('SK', 'SVK', '703', 'EU', 'Slovakia', 'the Slovak Republic', 'Bratislava'),
('SI', 'SVN', '705', 'EU', 'Slovenia', 'the Republic of Slovenia', 'Ljubljana'),
('SB', 'SLB', '090', 'OC', 'Solomon Islands', 'Solomon Islands', 'Honiara'),
('SO', 'SOM', '706', 'AF', 'Somalia', 'the Federal Republic of Somalia', 'Mogadishu'),
('ZA', 'ZAF', '710', 'AF', 'South Africa', 'the Republic of South Africa', 'Pretoria'),
('GS', 'SGS', '239', 'AN', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'King Edward Point'),
('SS', 'SSD', '728', 'AF', 'South Sudan', 'the Republic of South Sudan', 'Juba'),
('ES', 'ESP', '724', 'EU', 'Spain', 'the Kingdom of Spain', 'Madrid'),
('LK', 'LKA', '144', 'AS', 'Sri Lanka', 'the Democratic Socialist Republic of Sri Lanka', 'Colombo'),
('SD', 'SDN', '729', 'AF', 'Sudan', 'the Republic of the Sudan', 'Khartoum'),
('SR', 'SUR', '740', 'SA', 'Suriname', 'the Republic of Suriname', 'Paramaribo'),
('SJ', 'SJM', '744', 'EU', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'Longyearbyen'),
('SZ', 'SWZ', '748', 'AF', 'Swaziland', 'the Kingdom of Swaziland', 'Mbabane'),
('SE', 'SWE', '752', 'EU', 'Sweden', 'the Kingdom of Sweden', 'Stockholm'),
('CH', 'CHE', '756', 'EU', 'Switzerland', 'the Swiss Confederation', 'Bern'),
('SY', 'SYR', '760', 'AS', 'Syrian Arab Republic', 'the Syrian Arab Republic', 'Damascus'),
('TW', 'TWN', '158', 'AS', 'Taiwan, Province of China', 'Taiwan, Province of China', 'Taipei'),
('TJ', 'TJK', '762', 'AS', 'Tajikistan', 'the Republic of Tajikistan', 'Dushanbe'),
('TZ', 'TZA', '834', 'AF', 'Tanzania, United Republic of', 'the United Republic of Tanzania', 'Dodoma'),
('TH', 'THA', '764', 'AS', 'Thailand', 'the Kingdom of Thailand', 'Bangkok'),
('TL', 'TLS', '626', 'AS', 'Timor-Leste', 'the Democratic Republic of Timor-Leste', 'Dili'),
('TG', 'TGO', '768', 'AF', 'Togo', 'the Togolese Republic', 'Lomé'),
('TK', 'TKL', '772', 'OC', 'Tokelau', 'Tokelau', ''),
('TO', 'TON', '776', 'OC', 'Tonga', 'the Kingdom of Tonga', 'Nuku\'alofa'),
('TT', 'TTO', '780', 'NA', 'Trinidad and Tobago', 'the Republic of Trinidad and Tobago', 'Port of Spain'),
('TN', 'TUN', '788', 'AF', 'Tunisia', 'the Republic of Tunisia', 'Tunis'),
('TR', 'TUR', '792', 'AS', 'Turkey', 'the Republic of Turkey', 'Ankara'),
('TM', 'TKM', '795', 'AS', 'Turkmenistan', 'Turkmenistan', 'Ashgabat'),
('TC', 'TCA', '796', 'NA', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'Cockburn Town'),
('TV', 'TUV', '798', 'OC', 'Tuvalu', 'Tuvalu', 'Funafuti'),
('UG', 'UGA', '800', 'AF', 'Uganda', 'the Republic of Uganda', 'Kampala'),
('UA', 'UKR', '804', 'EU', 'Ukraine', 'Ukraine', 'Kiev'),
('AE', 'ARE', '784', 'AS', 'United Arab Emirates', 'the United Arab Emirates', 'Abu Dhabi'),
('GB', 'GBR', '826', 'EU', 'United Kingdom', 'the United Kingdom of Great Britain and Northern Ireland', 'London'),
('UM', 'UMI', '581', 'NA', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', ''),
('US', 'USA', '840', 'NA', 'United States of America', 'the United States of America', 'Washington'),
('UY', 'URY', '858', 'SA', 'Uruguay', 'the Eastern Republic of Uruguay', 'Montevideo'),
('UZ', 'UZB', '860', 'AS', 'Uzbekistan', 'the Republic of Uzbekistan', 'Tashkent'),
('VU', 'VUT', '548', 'OC', 'Vanuatu', 'the Republic of Vanuatu', 'Port Vila'),
('VE', 'VEN', '862', 'SA', 'Venezuela', 'the Bolivarian Republic of Venezuela', 'Caracas'),
('VN', 'VNM', '704', 'AS', 'Viet Nam', 'the Socialist Republic of Viet Nam', 'Hanoi'),
('VG', 'VGB', '092', 'NA', 'Virgin Islands (British)', 'the British Virgin Islands', 'Road Town'),
('VI', 'VIR', '850', 'NA', 'Virgin Islands (U.S.)', 'the Virgin Islands of the United States', 'Charlotte Amalie'),
('WF', 'WLF', '876', 'OC', 'Wallis and Futuna', 'Wallis and Futuna Islands', 'Mata-Utu'),
('EH', 'ESH', '732', 'AF', 'Western Sahara', 'Western Sahara', 'El Aaiún'),
('YE', 'YEM', '887', 'AS', 'Yemen', 'the Republic of Yemen', 'Sana\'a'),
('ZM', 'ZMB', '894', 'AF', 'Zambia', 'the Republic of Zambia', 'Lusaka'),
('ZW', 'ZWE', '716', 'AF', 'Zimbabwe', 'the Republic of Zimbabwe', 'Harare');